// ── Personal info ──────────────────────────────────────────
export const personal = {
  name: 'Eric Ayestaran',
  fullName: 'Eric Ayestaran Guillorme',
  email: 'ericayestaran@hotmail.com',
  phone: '+34 688 621 300',
  github: 'https://github.com/eric-ayes',
  linkedin: 'https://www.linkedin.com/in/eric-ayestaran/',
  location: 'Madrid, Spain',
};

// ── i18n strings ───────────────────────────────────────────
export const i18n = {
  es: {
    nav: { projects: 'proyectos', about: 'sobre mí', contact: 'contacto' },
    hero: {
      tag: 'AI Engineer · Madrid',
      headline: 'I build things',
      headlineSub: 'that work.',
      sub: 'Ingeniero de Deep Learning con bases teóricas sólidas. Visión por computador, vídeo, señal, LLMs y agentes de IA. EHU · UAM · CIC biomaGUNE.',
      cta: 'Ver proyectos',
    },
    sections: { projects: 'Proyectos', about: 'Sobre mí', contact: 'Contacto' },
    about: {
      title: 'Engineer first.\nTheory-backed.',
      p1: 'Graduado en IA por la EHU, máster en Deep Learning (audio, vídeo e imagen) en la UAM. Entiendo los modelos por dentro y los hago funcionar en la práctica.',
      p2: 'He trabajado con datos reales en investigación aplicada (CIC biomaGUNE), en entornos empresariales (Zitu Informatika) y con benchmarks estándar del campo. También diseño sistemas con agentes de IA y automatización de procesos.',
      skillGroups: [
        { label: 'Deep Learning & ML', skills: ['PyTorch', 'Computer Vision', 'Video Understanding', 'Signal Processing', 'Self-supervised', 'Transformers', 'Biometrics'] },
        { label: 'LLMs & Agentes', skills: ['LLM Fine-tuning', 'AI Agents', 'RAG', 'Process Automation', 'MLOps'], hot: true },
        { label: 'Tools & Stack', skills: ['Python', 'sklearn', 'NumPy', 'Git', 'Docker', 'Linux', 'Jupyter'] },
      ],
      eduLabel: 'Educación',
      expLabel: 'Experiencia',
    },
    contact: {
      pre: 'Open to work · Colaboraciones · Research',
      or: 'o encuéntrame en',
    },
    finishing: 'TFM en curso',
    collab: 'colaboración',
    current: 'En curso',
    research: 'Investigación',
    industry: 'Empresa',
  },
  en: {
    nav: { projects: 'projects', about: 'about', contact: 'contact' },
    hero: {
      tag: 'AI Engineer · Madrid',
      headline: 'I build things',
      headlineSub: 'that work.',
      sub: 'Deep learning engineer with solid theoretical foundations. Computer vision, video, signal processing, LLMs and AI agents. EHU · UAM · CIC biomaGUNE.',
      cta: 'View projects',
    },
    sections: { projects: 'Projects', about: 'About', contact: 'Contact' },
    about: {
      title: 'Engineer first.\nTheory-backed.',
      p1: 'BSc in AI from EHU, MSc in Deep Learning (audio, video & image) at UAM. I understand models inside out and make them work in practice.',
      p2: "I've worked with real data in applied research (CIC biomaGUNE), industry internships (Zitu Informatika), and standard benchmarks. I also design AI agent systems and process automation pipelines.",
      skillGroups: [
        { label: 'Deep Learning & ML', skills: ['PyTorch', 'Computer Vision', 'Video Understanding', 'Signal Processing', 'Self-supervised', 'Transformers', 'Biometrics'] },
        { label: 'LLMs & Agents', skills: ['LLM Fine-tuning', 'AI Agents', 'RAG', 'Process Automation', 'MLOps'], hot: true },
        { label: 'Tools & Stack', skills: ['Python', 'sklearn', 'NumPy', 'Git', 'Docker', 'Linux', 'Jupyter'] },
      ],
      eduLabel: 'Education',
      expLabel: 'Experience',
    },
    contact: {
      pre: 'Open to work · Collaborations · Research',
      or: 'or find me at',
    },
    finishing: 'Finishing TFM',
    collab: 'collaboration',
    current: 'In progress',
    research: 'Research',
    industry: 'Industry',
  },
};

// ── Timeline ───────────────────────────────────────────────
export const timeline = {
  education: [
    { year: '2025–2026', titleEs: 'Máster en Deep Learning', titleEn: 'MSc in Deep Learning', sub: 'UAM · Audio, vídeo e imagen', badge: 'current' },
    { year: '2021–2025', titleEs: 'Grado en Inteligencia Artificial', titleEn: 'BSc in Artificial Intelligence', sub: 'EHU / UPV', badge: 'research' },
  ],
  experience: [
    { year: '2024', titleEs: 'Prácticas · AI / Dev', titleEn: 'Internship · AI / Dev', sub: 'Zitu Informatika', badge: 'industry' },
    { year: '2024–2025', titleEs: 'TFG · ML Aplicado', titleEn: 'Bachelor Thesis · Applied ML', sub: 'CIC biomaGUNE', badge: 'research' },
  ],
};

// ── Projects ───────────────────────────────────────────────
export const projects = [
  {
    id: 'tfm-mri',
    featured: true,
    domainEs: 'Vision · Generativa · Medical AI',
    domainEn: 'Vision · Generative · Medical AI',
    titleEs: 'Síntesis de Imagen Sintética y Domain Adaptation para Segmentación MRI',
    titleEn: 'Synthetic Image Generation & Domain Adaptation for Missing Modalities in MRI Segmentation',
    descEs: 'TFM en curso. Generación de imágenes sintéticas para modalidades MRI faltantes y domain adaptation para segmentación robusta con datos incompletos.',
    descEn: "Master's thesis (in progress). Synthetic generation for missing MRI modalities. Domain adaptation for robust segmentation with incomplete data.",
    metric: 'GANs · Diffusion · Domain Adaptation',
    metricType: 'blue',
    badge: 'finishing',
    github: null,
  },
  {
    id: 'mot16',
    domainEs: 'Vídeo · Tracking',
    domainEn: 'Video · Tracking',
    titleEs: 'Multi-Object Tracking MOT16',
    titleEn: 'Multi-Object Tracking MOT16',
    descEs: 'ByteTrack + NSA Kalman Filter + Re-ID con ResNet-18. Pipeline completo de detección a tracking robusto.',
    descEn: 'ByteTrack + NSA Kalman Filter + Re-ID with ResNet-18. Full pipeline from detection to robust tracking.',
    metric: 'MOTA 26 → 68%',
    metricType: 'accent',
    github: 'https://github.com/eric-ayes/dl-video-challenge-mot16',
  },
  {
    id: 'deepfakes',
    domainEs: 'Visión · Biometría · Security AI',
    domainEn: 'Vision · Biometrics · Security AI',
    titleEs: 'Biometría y Detección de Deepfakes',
    titleEn: 'Biometrics & Deepfake Detection',
    descEs: 'Laboratorio de biometría e inteligencia aplicada. Detección de deepfakes y verificación biométrica con deep learning.',
    descEn: 'Biometrics and applied AI lab. Deepfake detection and biometric verification with deep learning.',
    metric: 'Deepfake Detection · Face Verification',
    metricType: 'default',
    github: 'https://github.com/eric-ayes/Biometrics_DeepFakes_Lab',
  },
  {
    id: 'enzyme',
    domainEs: 'Señal · BioTech · Applied ML',
    domainEn: 'Signal · BioTech · Applied ML',
    titleEs: 'ML para Adhesión Enzimática',
    titleEn: 'Enzyme Adhesion ML',
    descEs: 'MiniROCKET, pseudo-labeling y MLML sobre datos biológicos reales. Colaboración con CIC biomaGUNE.',
    descEn: 'MiniROCKET, pseudo-labeling and MLML on real biological data. Collaboration with CIC biomaGUNE.',
    metric: 'Real-world research data',
    metricType: 'accent',
    github: 'https://github.com/eric-ayes/tfg-enzyme-adhesion-ml',
  },
  {
    id: 'segmentation',
    domainEs: 'Visión · Segmentación',
    domainEn: 'Vision · Segmentation',
    titleEs: 'Segmentación Semántica',
    titleEn: 'Semantic Segmentation',
    descEs: 'PSPNet sobre PASCAL VOC con weighted loss para clases desbalanceadas. Comparativa FCN / DeepLabv3.',
    descEn: 'PSPNet on PASCAL VOC with weighted loss for class imbalance. FCN / DeepLabv3 comparison.',
    metric: 'PSPNet · mIoU · DeepLabv3',
    metricType: 'default',
    github: 'https://github.com/eric-ayes/dl-image-lab3-semantic-segmentation',
  },
  {
    id: 'detection',
    domainEs: 'Visión · Detección',
    domainEn: 'Vision · Detection',
    titleEs: 'Detección de Objetos',
    titleEn: 'Object Detection',
    descEs: 'YOLO loss, Focal Loss, diseño de anchors y evaluación con mAP sobre PASCAL VOC.',
    descEn: 'YOLO loss, Focal Loss, anchor design and mAP evaluation on PASCAL VOC.',
    metric: 'YOLO · Focal Loss · mAP',
    metricType: 'default',
    github: 'https://github.com/eric-ayes/dl-image-lab4-object-detection',
  },
  {
    id: 'video-cls',
    domainEs: 'Vídeo · Clasificación',
    domainEn: 'Video · Classification',
    titleEs: 'Clasificación de Vídeo UCF101',
    titleEn: 'Video Classification UCF101',
    descEs: 'InceptionV3 + CNN-LSTM para reconocimiento de acciones temporales sobre UCF101.',
    descEn: 'InceptionV3 + CNN-LSTM for temporal action recognition on UCF101.',
    metric: 'CNN-LSTM · InceptionV3',
    metricType: 'default',
    github: 'https://github.com/eric-ayes/dl-video-lab1-classification',
  },
  {
    id: 'ssl',
    domainEs: 'Visión · Self-supervised',
    domainEn: 'Vision · Self-supervised',
    titleEs: 'Self-supervised Learning',
    titleEn: 'Self-supervised Learning',
    descEs: 'Rotation pretext task con ResNet-14/18. Evaluación de representaciones sin etiquetas.',
    descEn: 'Rotation pretext task with ResNet-14/18. Label-free representation evaluation.',
    metric: 'Pretext Task · Linear Probe',
    metricType: 'default',
    github: 'https://github.com/eric-ayes/dl-image-lab2-self-supervised',
  },
  {
    id: 'cls',
    domainEs: 'Visión · Clasificación',
    domainEn: 'Vision · Classification',
    titleEs: 'Clasificación de Imagen',
    titleEn: 'Image Classification',
    descEs: 'SimpleCNN, AlexNet, ResNet, Transfer Learning y Data Augmentation con PyTorch.',
    descEn: 'SimpleCNN, AlexNet, ResNet, Transfer Learning and Data Augmentation with PyTorch.',
    metric: 'ResNet · Transfer Learning',
    metricType: 'default',
    github: 'https://github.com/eric-ayes/dl-image-lab1-classification',
  },
  {
    id: 'music-gen',
    domainEs: 'Audio · Generativa',
    domainEn: 'Audio · Generative',
    titleEs: 'Generación de Música',
    titleEn: 'Music Generation',
    descEs: 'Generación de música con deep learning. Proyecto colaborativo.',
    descEn: 'Music generation with deep learning. Collaborative project.',
    metric: 'Audio Generation · Collab',
    metricType: 'default',
    collab: true,
    github: 'https://github.com/Tuneful13/music_gen',
  },
];
